# Generated by Django 4.2.30 on 2026-06-21 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0005_tag_birthday_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'тег', 'verbose_name_plural': 'теги'},
        ),
    ]
